apiVersion: v1
kind: ServiceAccount
metadata:
  name: janitor-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: janitor-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "delete"] # 파드 조회 및 삭제 권한
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: janitor-binding
subjects:
  - kind: ServiceAccount
    name: janitor-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: janitor-role
  apiGroup: rbac.authorization.k8s.io