apiVersion: v1
kind: Secret
metadata:
  name: janitor-secret
  namespace: default
type: Opaque
stringData:
  # K8s 내부에서 MySQL을 찾을 주소 (Service 이름)
  # (주의: MySQL 서비스 이름이 'mysql'이 아니면 수정 필요)
  DB_HOST: "mysql.default.svc.cluster.local"
  DB_USER: "root"
  DB_PASSWORD: "1234" # 실제 비밀번호로 변경
  DB_NAME: "janitor_db"